### ISSUE TITLE
Cannot build: can't find `aligned_alloc`

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/FBGEMM#1]
I try to build on my mac and get this:

```
In file included from /Users/jamesreed/FBGEMM/src/FbgemmFP16.cc:7:
/Users/jamesreed/FBGEMM/include/fbgemm/FbgemmFP16.h:67:24: error: use of undeclared identifier 'aligned_alloc'
    pmat_ = (float16 *)aligned_alloc(64, matSize() * sizeof(float16) + padding);
```

There are some workarounds described here https://stackoverflow.com/questions/29247065/compiler-cant-find-aligned-alloc-function but I haven't gotten them to work with LLVM on mac

**Comment by dskhudia** [comment]
Fixed in the recent commit :)
