### ISSUE TITLE
Update to asmjit latest

### ISSUE THREAD

**Issue by stevemk14ebr** [pytorch/FBGEMM#1070]
Hello, the vcpkg port for asmjit will be updated soon, please see https://github.com/microsoft/vcpkg/pull/24362. Can this repository please update to head and then push a port update? The current port fails with the updated asmjit port. If this update cannot be done, can the fbgemm port be removed instead, it is blocking the update of asmjit due to the lack of version pinning in vcpkg.

**Comment by jianyuh** [comment]
We are working on the update. Currently trying to resolve some issues on Mac build. Maybe @geyyer can put a PR for the users to have the early access to the code with the latest asmjit.

**Comment by geyyer** [comment]
Thanks, @jianyuh! Hi @stevemk14ebr, here is the PR https://github.com/pytorch/FBGEMM/pull/1077, looks like there are still some build issues, working on it!

**Comment by jianyuh** [comment]
https://github.com/pytorch/FBGEMM/pull/1096 is the latest which can pass ubuntu build (still some issues with Mac build).

**Comment by stevemk14ebr** [comment]
Hi, bumping this, any updates? The asmtk port is now fixed on vcpkg, which leaves asmjit the only port left to update to unblock my own port update (polyhook2). We can't move forward with asmjit until this project itself is updated.

**Comment by jianyuh** [comment]
cc @mjanderson09 , @geyyer , @jspark1105

**Comment by mjanderson09** [comment]
Thank you @stevemk14ebr , we are making this a top priority item and will let you know as soon as we have a better time estimate.

**Comment by stevemk14ebr** [comment]
looking forward to the merge, it will be a big help

**Comment by mjanderson09** [comment]
Hi @stevemk14ebr , we've resolved the issues we were having with the asmjit upgrade and should be landing the new version in the next few days. Thank you for your patience.

**Comment by stevemk14ebr** [comment]
When you do that version release can you submit a PR to update the portfile here: https://github.com/microsoft/vcpkg/tree/c9e786d81a890ef6b3932779925f11e696dc9541/ports/fbgemm I'll try to coordinate that with the updates to asmjit in this thread: https://github.com/microsoft/vcpkg/tree/c9e786d81a890ef6b3932779925f11e696dc9541/ports/fbgemm

**Comment by jianyuh** [comment]
@stevemk14ebr  We are landing the PR https://github.com/pytorch/FBGEMM/pull/1077 soon (ETA tomorrow).

**Comment by stevemk14ebr** [comment]
Can you fix the vcpkg port. The existing port uses a patchfile to the cmakelists, and this is not compatible with the current cmakelists.

**Comment by gvavvari** [comment]
@stevemk14ebr I started working on this issue. However, without the latest asmjit, our latest port fix for fbgemm might still fail. I will submit a pull request for fbgemm by end of today.

**Comment by stevemk14ebr** [comment]
Thanks so much!! Yea I understand the issue, as long as FBGEMMs port assumes the latest asmjit all is well. Your PR will stay open for a bit while I update asmjit, polyhook2, and add asmtk. Then once those are all in we can merge at the same time and everyone wi be on the latest finally. I'd do it myself but the FBGEMMs cmake git patch in vcpkg is too complex for me to understand.

**Comment by stevemk14ebr** [comment]
vcpkg\ports\asmjit\portfile.cmake:
```
vcpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  REPO asmjit/asmjit
  REF 052b4430e93f021709d27d2b5d42694ce0c49ce6 # accessed on 2022-09-22
  SHA512 5c12b0fda4f0469b44f8035a67a70e782d458bf6064275a7ffc3c7e125fa95598dad62fc6cb390a77ea1bb33d76ddc876505cc036bc71273b3a22a910bd688a9
  HEAD_REF master
)
```

vcpkg\ports\fbgemm\portfile.cmake:
```
# The project's CMakeLists.txt uses Python to select source files. Check if it is available in advance.
vcpkg_find_acquire_program(PYTHON3)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO pytorch/fbgemm
    REF 8e9cc8b116a04d1a0d8e8a2eedbf3c6885171765
    SHA512 13435ea8c50e465632b3a8405c5a305413a286fbee0035daca9952b259f0145afe80146fe96bda49e37d8963560f7852613f20369bc7a291242491de8b3d612d
    PATCHES
        fix-cmakelists.patch
)
```

build error:
```
[64/66] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe   /TP -DCPUINFO_SUPPORTED_PLATFORM=1 -DFBGEMM_STATIC -IC:\Users\steve\source\repos\vcpkg\buildtrees\fbgemm\src\6885171765-39d8acbcca.clean\include -IC:\Users\steve\source\repos\vcpkg\buildtrees\fbgemm\src\6885171765-39d8acbcca.clean -external:IC:\Users\steve\source\repos\vcpkg\installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  -openmp /wd4244 /wd4267 /wd4305 /wd4309 /wd4703 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++14 /showIncludes /FoCMakeFiles\fbgemm_generic.dir\src\EmbeddingSpMDM.cc.obj /FdCMakeFiles\fbgemm_generic.dir\ /FS -c C:\Users\steve\source\repos\vcpkg\buildtrees\fbgemm\src\6885171765-39d8acbcca.clean\src\EmbeddingSpMDM.cc
FAILED: CMakeFiles/fbgemm_generic.dir/src/EmbeddingSpMDM.cc.obj 
C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe   /TP -DCPUINFO_SUPPORTED_PLATFORM=1 -DFBGEMM_STATIC -IC:\Users\steve\source\repos\vcpkg\buildtrees\fbgemm\src\6885171765-39d8acbcca.clean\include -IC:\Users\steve\source\repos\vcpkg\buildtrees\fbgemm\src\6885171765-39d8acbcca.clean -external:IC:\Users\steve\source\repos\vcpkg\installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  -openmp /wd4244 /wd4267 /wd4305 /wd4309 /wd4703 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++14 /showIncludes /FoCMakeFiles\fbgemm_generic.dir\src\EmbeddingSpMDM.cc.obj /FdCMakeFiles\fbgemm_generic.dir\ /FS -c C:\Users\steve\source\repos\vcpkg\buildtrees\fbgemm\src\6885171765-39d8acbcca.clean\src\EmbeddingSpMDM.cc
C:\Users\steve\source\repos\vcpkg\buildtrees\fbgemm\src\6885171765-39d8acbcca.clean\src\EmbeddingSpMDM.cc : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
ninja: build stopped: subcommand failed.
```
