### ISSUE TITLE
Poor error message for Conv when parameters are incompatible

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/FBGEMM#115]
Message:

```
RuntimeError: [FBGEMM_CONV_ERROR] Prepacked weights can't be used with these convolution parameters!
```

In particular, this does not tell me anything about *why* it cannot be used with these parameters, *which* parameters are incompatible, or *what* I should do to fix it

**Comment by jianyuh** [comment]
@dskhudia is fixing this: https://github.com/pytorch/FBGEMM/pull/117

**Comment by jianyuh** [comment]
Closed as https://github.com/pytorch/FBGEMM/pull/117 is merged.
