### ISSUE TITLE
Confused about FUSE_RELU flag

### ISSUE THREAD

**Issue by WANGSSSSSSS** [pytorch/FBGEMM#1150]
the outporcess function (requantize) use FUSE_RELU flag to indicate to clamp the value between zero-point - 255 
So is this FUSE_RELU flag redundant when the zero point and scale of activation is calculated from relu instead of the previous conv layer?

**Comment by jiyuanzFB** [comment]
yes we assume the zero point and scale should be based on values of conv layer. FUSE_RELU clamps the value after the requantization.
