### ISSUE TITLE
Error while importing fbgemm_gpu.split_table_batched_embeddings_ops

### ISSUE THREAD

**Issue by agunapal** [pytorch/FBGEMM#1151]
I am trying to use fbgemm_gpu on CPU (Ubuntu 18.04)
I built it from source with 
~/FBGEMM/fbgemm_gpu$ python setup.py install --cpu_only

I am getting this error when I am importing fbgemm_gpu.split_table_batched_embeddings_ops

>>> import fbgemm_gpu
>>> import fbgemm_gpu.split_table_batched_embeddings_ops as split_table_batched_embeddings_ops
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fbgemm_gpu.split_table_batched_embeddings_ops'
>>> 

Please let me know if you need any additional inputs

**Comment by mjanderson09** [comment]
Thanks Ankith for bringing this up, we're taking a look right now.

**Comment by MohammadMahdiJavanmard** [comment]
Ankith, could you please run "pip list" and check whether fbgemm-gpu is listed as one of the installed packages?

**Comment by agunapal** [comment]
@MohammadMahdiJavanmard  Yes it is 
pip list | grep -i fbgemm
fbgemm-gpu           0.1.1

**Comment by MohammadMahdiJavanmard** [comment]
Ankith, we want to ensure that env variable [PYTHONPATH](https://docs.python.org/3.8/using/cmdline.html#envvar-PYTHONPATH) is set properly. Also, could you please ensure that int the python installation directory (in site-packages), you have a directory corresponding to fbgemm-gpu and it contains the shared object file (perhaps named fbgemm_gpu_py.so?)?

**Comment by mjanderson09** [comment]
Hi @agunapal were you able to get the install working with the suggestions above? If so I can close the issue. Thank you!

**Comment by agunapal** [comment]
@mjanderson09  Thank you! Yes, With @MohammadMahdiJavanmard 's help, we figured out that the problem was that fbgemm_gpu was installed without installing FBGEMM first. Will close the issue
