### ISSUE TITLE
fbgemm.permute_2D_sparse_data RuntimeError: Tensors of type TensorImpl do not have numel

### ISSUE THREAD

**Issue by RenfeiChen-FB** [pytorch/FBGEMM#1167]
How to reproduce:

conda install -y pytorch cudatoolkit=11.3 -c pytorch-nightly
pip install --pre torchrec_nightly -f https://download.pytorch.org/whl/nightly/torchrec_nightly/index.html
(Torchrec_nightly build the latest FBGemm from source)

torchx run -s local_cwd dist.ddp -j 1x2 --script test_installation.py (inside torchrec github)

How to fix:

conda install -y pytorch=1.13.0.dev20220620 cudatoolkit=11.3 -c pytorch-nightly

What's the root cause:

FBGemm cannot work with the latest pytorch-nightly (20220621), 0620 is good

**Comment by geyyer** [comment]
Thanks, @RenfeiChen-FB! Looks like the pytorch-nightly is fixed now, closing the issue!
