### ISSUE TITLE
Runtime query if machine has required instruction sets

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/FBGEMM#12]
This code path: https://github.com/pytorch/FBGEMM/blob/25ab38b1106e2f795d2f4cc40a4f0338e1137771/src/PackMatrix.cc#L54

Causes failures when integrating FBGEMM into PyTorch at the moment. A possible alternative is to provide an API for the framework (PyTorch) to query so that it can select between the FBGEMM specialized version of the operator or the default version. Can we export a simple API that returns a boolean describing--at runtime--whether we are on a machine that supports the necessary AVX instructions?

**Comment by dskhudia** [comment]
Hi @jamesr66a,

FBGEMM only supports instruction sets avx2 and above. So currently IMO calling FBGEMM functions only on machines with avx2 or higher instruction set is the viable option. 

We do have a plan to provide a default path but that will be very slow and we have no plans to optimize this default path for instruction sets < avx2. 

Thanks
Daya

**Comment by dskhudia** [comment]
https://github.com/pytorch/FBGEMM/pull/13

**Comment by dskhudia** [comment]
Hi @jamesr66a ,

Is the provided function sufficient for the use case you were looking for?

**Comment by jamesr66a** [comment]
@dskhudia yes, it looks good to me. Thanks!
