### ISSUE TITLE
PyTorch can't use latest FBGEMM because of asmjit includes in Utils.h

### ISSUE THREAD

**Issue by powderluv** [pytorch/FBGEMM#1227]
Rolling PyTorch with latest [FBGEMM](https://github.com/pytorch/pytorch/pull/82396) fails with https://github.com/pytorch/pytorch/runs/7562032160?check_suite_focus=true 

```

[ 40%] Building C object confu-deps/XNNPACK/CMakeFiles/all_microkernels.dir/src/qs8-gemm/gen/4x4-minmax-fp32-scalar-imagic.c.o
In file included from /var/lib/jenkins/workspace/caffe2/quantization/server/group_norm_dnnlowp_op_avx2.cc:10:
In file included from /var/lib/jenkins/workspace/third_party/fbgemm/include/fbgemm/QuantUtils.h:6:
/var/lib/jenkins/workspace/third_party/fbgemm/include/fbgemm/./Utils.h:18:10: fatal error: 'asmjit/asmjit.h' file not found
#include <asmjit/asmjit.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [caffe2/quantization/server/CMakeFiles/caffe2_dnnlowp_avx2_ops.dir/build.make:104: caffe2/quantization/server/CMakeFiles/caffe2_dnnlowp_avx2_ops.dir/group_norm_dnnlowp_op_avx2.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 40%] Building C object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/qc8-igemm/gen/4x16c8-minmax-fp32-avx512skx.c.o

```

This seems to have been added recently with https://github.com/pytorch/FBGEMM/commit/64a5c4a9f7f18cbf0e2afcaa561d96c949afd950 in PR https://github.com/pytorch/FBGEMM/pull/1077

**Comment by jianyuh** [comment]
Thanks for reporting! It's weird to see this issue. I thought <asmjit/asmjit.h> can be always found with any asmjit commits.

I just launched 2 PRs for further testing: right before asmjit upgrade (https://github.com/pytorch/pytorch/pull/82630) and right before asmjit upgrade to the latest (https://github.com/pytorch/pytorch/pull/82631).

**Comment by jianyuh** [comment]
OK: it's the issue from <asmjit/asmjit.h> dependency added in Utils.h in PR https://github.com/pytorch/FBGEMM/pull/1077

I tried some workaround to spin off the simd_info struct which contains <asmjit/asmjit.h>, and it seems to work so far:
https://github.com/pytorch/pytorch/pull/82637

**Comment by jianyuh** [comment]
https://github.com/pytorch/FBGEMM/pull/1233 is landed. Closing this issue.

**Comment by jianyuh** [comment]
https://github.com/pytorch/pytorch/pull/82676 in PyTorch is merged.
