### ISSUE TITLE
Is this available on windows?

### ISSUE THREAD

**Issue by snaik2016** [pytorch/FBGEMM#150]
Can this library be built on windows?

**Comment by dskhudia** [comment]
Hi @snaik2016, 

We haven't tried building it on windows. We expect some issues as we generate code at runtime and the calling convention is different with windows compiler + platform. There may be some compiler incompatibility issues as well. However, we don't expect any major changes. Currently the support on windows platform is not planned to be added in near future but we welcome external contributions. 

Thanks
Daya

**Comment by peterjc123** [comment]
I tried with https://github.com/pytorch/FBGEMM/pull/238. Due to the fact that I don't have too much knowledge about assembly code, I cannot proceed any further. Could you please take a look there?

**Comment by dskhudia** [comment]
@peterjc123 Thanks for your contributions. Let me look at your PR. I have been making some progress on this with https://github.com/pytorch/FBGEMM/commit/d06ea705ff58cc75d24f9f1e41b94f09083921b7 https://github.com/pytorch/FBGEMM/commit/c960d51570bb880505d3c4073c02309861f23bed https://github.com/pytorch/FBGEMM/commit/fc3dfe3e0a4e662146adc8daf344ab7feecdff60 and others recently.

**Comment by ykim362** [comment]
Actually, I've made FBGEMM fully functional on windows. https://github.com/marian-nmt/FBGEMM
It's based on https://github.com/marian-nmt/FBGEMM/commit/518d8a1832cf1eb1dda2feace1a278e9e4f302ba.

I could do rebase on the latest branch, if needed.
I am aware of there are some new code including AVX512 based fp16.

**Comment by shz0116** [comment]
> Can this library be built on windows?

@snaik2016 we are trying to port the code to Windows platform. One question is whether you need both Static and Shared FBGEMM libraries, or just static ? Do you know how important shared library is on Windows platforms compared with static ?
Icc @peterjc123 and @ykim362 @dskhudia @jspark1105

**Comment by ykim362** [comment]
@shz0116 In my use case in marian-nmt, I directly include those file into my VS project. And, the mother VS project generates a shared library (dll). So, I am using a shared library, but I only include files I need in the project. I use ' FBGEMM_EXPORTS' definition in the project.

**Comment by shz0116** [comment]
@ykim362 so you have not seen the problem in [https://github.com/pytorch/FBGEMM/issues/266](url) ?

**Comment by ykim362** [comment]
@shz0116 I don't have a problem in my forked branch. ( https://github.com/marian-nmt/FBGEMM ). I might need to merge the latest FBGEMM branch into marian-nmt, soon. So, I will let you know how it goes.

**Comment by ykim362** [comment]
@shz0116 I can see one difference with the old version and the latest version. 'FBGEMM_EXPORTS' is forcely defined in some cc files in the latest version. 
e.g. https://github.com/pytorch/FBGEMM/blob/27cb280170fbf530033c4d0123e063e2f8bb50f3/src/PackAWithQuantRowOffset.cc#L7

Could this cause potential mismatches between dllimport and dllexport?
In the PackAWithQuantRowOffset.cc file, it's defined with **dllexport** because of the definition. On the other hand, in other files (e.g. PackedFloatInOutBenchmark.cc), Fbgemm.h is included without FBGEMM_EXPORTS resulting **dllimport**.

**Comment by peterjc123** [comment]
> > Can this library be built on windows?
> 
> @snaik2016 we are trying to port the code to Windows platform. One question is whether you need both Static and Shared FBGEMM libraries, or just static ? Do you know how important shared library is on Windows platforms compared with static ?
> Icc @peterjc123 and @ykim362 @dskhudia @jspark1105

I guess the static build is okay if the size is not too big. Otherwise, it will fail in the linking stage because PyTorch is already large enough.

**Comment by peterjc123** [comment]
The shared build should be working in https://github.com/pytorch/FBGEMM/pull/268.

**Comment by dskhudia** [comment]
FBGEMM works on window now. Closing this issue.
