### ISSUE TITLE
make install: make: *** No rule to make target 'install'.  Stop.

### ISSUE THREAD

**Issue by tiepvupsu** [pytorch/FBGEMM#1555]
I have tried to following the instruction in the README.md without success. 
![image](https://user-images.githubusercontent.com/2201237/213848370-693c7a79-0eb7-4b8e-987d-37cf58e2f55f.png)

While the selected code block in the screenshot is working ok, the other two `make` commands do not seem to work:

```
% make test
make: Nothing to be done for 'test'.
% make install 
make: *** No rule to make target 'install'.  Stop.
```

Not sure if I'm missing something. Please take a look. Thank you.

**Comment by shintaro-iwasaki** [comment]
@tiepvupsu Thanks for reporting an issue! And sorry for the late reply.

To run FBGEMM tests, you need to move to the `build` directory.

```sh
cmake -B build
make -C build
cd build # <- this line is needed.
make test
```
We will update `FBGEMM/README.md`.  Thanks for pointing it out!

Just in case: If you want to use a GPU version, please check `FBGEMM/fbgemm_gpu/README.md`.

**Comment by q10** [comment]
This is now addressed by README changes made as part of https://github.com/pytorch/FBGEMM/pull/1582
