### ISSUE TITLE
`use_cpu=st.booleans()` in `jagged_index_select_2d_ref` fails the test on ROCm

### ISSUE THREAD

**Issue by liligwu** [pytorch/FBGEMM#1636]
The test jagged_index_select_2d_ref fails if `use_cpu=True` on ROCm, https://github.com/pytorch/FBGEMM/blob/8616ed701015f8b9e4c2825ce592b204b4cfaf28/fbgemm_gpu/test/jagged_tensor_ops_test.py#L1469 

The issue is akin to https://github.com/pytorch/FBGEMM/blob/8616ed701015f8b9e4c2825ce592b204b4cfaf28/fbgemm_gpu/test/split_table_batched_embeddings_test.py#L1009

A PR is opened to disable the CPU test on ROCm
https://github.com/pytorch/FBGEMM/pull/1635

**Comment by q10** [comment]
@liligwu Is the issue considered resolved now that https://github.com/pytorch/FBGEMM/pull/1635 has merged?

**Comment by liligwu** [comment]
> @liligwu Is the issue considered resolved now that #1635 has merged?

Yes, I'm closing it. Thank you for reminding me.
