### ISSUE TITLE
Is FBGEMM-GPU support aarch64 arch?

### ISSUE THREAD

**Issue by Qiyu8** [pytorch/FBGEMM#1693]
I want to build FBGEMM under ARM-based machine, but there is a compile error :
g++: error: unrecognized command line option '-mavx'
g++: error: unrecognized command line option '-mf16c'
g++: error: unrecognized command line option '-mfma'
g++: error: unrecognized command line option '-mavx2'
GPU code should not coupled with X86 arch, Is FBGEMM-GPU support aarch64 arch?

**Comment by q10** [comment]
Hi @Qiyu8, thanks for pointing out this issue.  Currently, FBGEMM_GPU is built and tested for x86 architecture, and there is no official support for ARM yet.   @shintaro-iwasaki would you happen to have insights into this effort?

**Comment by shintaro-iwasaki** [comment]
Thank you for letting us know! We cannot give an exact ETA at this point, we are looking at this issue.

**Comment by q10** [comment]
Hi @Qiyu8, FBGEMM_GPU v0.5.0 was released last week, and has introduced support for aarch64:

```
pip install fbgemm-gpu --index-url https://download.pytorch.org/whl/cpu/
```

Please see the release notes [here](https://github.com/pytorch/FBGEMM/releases/tag/v0.5.0).
