### ISSUE TITLE
Add some CLI args to set M,N,K to GEMMsBenchmark

### ISSUE THREAD

**Issue by WilliamTambellini** [pytorch/FBGEMM#1720]
Hi,
Would you mind if I add few CLI args to set M, N and/or K for GEMMsBenchmark:
https://github.com/pytorch/FBGEMM/blob/main/bench/GEMMsBenchmark.cc
eg:
./GEMMsBenchmark -M 13263 -N 242 -K 2821
?

**Comment by q10** [comment]
Hi @WilliamTambellini yes, absolutely, please feel free to open a PR that we can review.

**Comment by WilliamTambellini** [comment]
closed by
https://github.com/pytorch/FBGEMM/pull/1721
