### ISSUE TITLE
Add CLI option to measure time breakdown in GEMM bench

### ISSUE THREAD

**Issue by WilliamTambellini** [pytorch/FBGEMM#1724]
In
https://github.com/pytorch/FBGEMM/blob/main/bench/GEMMsBenchmark.cc
there is a define in order to measure and log the time breakdown.
Would you mind if I convert it to a runtime cli arg ? 
eg
./GEMMsBenchmark --timebreakdown=1
default 0

**Comment by q10** [comment]
Hi @WilliamTambellini sure, please feel free to open a PR for us to review

**Comment by WilliamTambellini** [comment]
done in
https://github.com/pytorch/FBGEMM/pull/1725
