### ISSUE TITLE
`.to("meta")` is exposed in sparse_ops_test

### ISSUE THREAD

**Issue by liligwu** [pytorch/FBGEMM#1789]
https://github.com/pytorch/FBGEMM/blob/f97fe45d327c17f9262956d743a1da541110fd60/fbgemm_gpu/test/sparse_ops_test.py#LL1693C21-L1693C21 exposes `.to("meta")` and causes a test error on ROCm.

> ======================================================================
> ERROR: test_pack_segments_meta_backend (__main__.SparseOpsTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "sparse_ops_test.py", line 1670, in test_pack_segments_meta_backend
>     n=st.integers(2, 10),
>   File "/opt/conda/lib/python3.8/site-packages/hypothesis/core.py", line 1145, in wrapped_test
>     raise the_error_hypothesis_found
>   File "sparse_ops_test.py", line 1699, in test_pack_segments_meta_backend
>     packed_tensor = torch.ops.fbgemm.pack_segments(
>   File "/opt/conda/lib/python3.8/site-packages/torch/_ops.py", line 499, in __call__
>     return self._op(*args, **kwargs or {})
> NotImplementedError: Could not run 'fbgemm::pack_segments' with arguments from the 'AutogradMeta' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'fbgemm::pack_segments' is only available for these backends: [CPU, CUDA, Meta, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].

**Comment by q10** [comment]
Hi @liligwu thanks for reporting this issue.  We will get back with a fix for this in the next few days.

**Comment by q10** [comment]
The fix has been merged, and will be deployed to the next nightly release.
