### ISSUE TITLE
Nightly packages should have same package name as regular packages

### ISSUE THREAD

**Issue by ezyang** [pytorch/FBGEMM#1920]
Currently fbgemm-gpu distributes nightlies named as fbgemm-gpu-nightly. This means you can have simultaneously have both fbgemm-gpu and fbgemm-gpu-nightly installed at the same time, which leads to obscure errors.

**Comment by shintaro-iwasaki** [comment]
Thanks for reporting an issue! If PyPI supports multiple channels, that'd be great, but it doesn't. Honestly I cannot come up with a good solution that does not increase a maintenance burden (with respect to the priority of fixing this issue), but your suggestions would be highly appreciated.

**[Background]** In my understand ...
1. First, we don't assume that normal people use a nightly package, so supporting nightly installation is not of high priority.
2. We use "PyPI" to host `fbgemm-gpu` and its nightly version. Unfortunately PyPi does not support multiple channels.
3. The second issue can be addressed by hosting a nightly at a different place. For example, PyTorch does the following, but this needs another host.
```bash
# stable (https://pypi.org/project/torch/)
pip3 install torch
# nightly
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
```

**Comment by ezyang** [comment]
Hi @shintaro-iwasaki. You don't have to prioritize this; and in any case it probably should be dev infra's job to fix this: https://github.com/pytorch/torchrec/issues/1313#issuecomment-1675567876 cc @colin2328 @henrylhtsang @osalpekar

**Comment by spcyppt** [comment]
@ezyang onboarded with Nova https://github.com/pytorch/FBGEMM/pull/2016. Package name is now fbgemm for both release and nightly, specifying version using --index-url, e.g., ```pip install fbgemm-gpu --index-url https://download.pytorch.org/whl/nightly/cu121```

We will deprecate versions on PyPI in the near future.
