### ISSUE TITLE
Any plan to publish fbgemm_gpu that supports cuda 12.1?

### ISSUE THREAD

**Issue by henrylhtsang** [pytorch/FBGEMM#1947]
Right now while the wheel for cuda 12.1 is built and tested, it is not being published. Curious is there a plan to change that?

https://github.com/pytorch/FBGEMM/blob/5b0e0de2937f57af7993c097c27d8fb2fbee15c6/.github/workflows/fbgemm_gpu_cuda_nightly.yml#L133C43-L133C43

cc @osalpekar

**Comment by shintaro-iwasaki** [comment]
Thanks for the question! Yes we test it for CUDA 12.1, but we don't publish the wheel, partly to avoid consuming too much PyPI storage (PyPI is not suitable for nightly). If we have a large space to upload it (with a good channel argument), we are very happy to publish all.

Currently we publish a wheel with the same CUDA version as what torch-nightly uses (#1954, cc @spcyppt).

**Comment by osalpekar** [comment]
@shintaro-iwasaki We can store the wheel on `download.pytorch.org` which is backed by the same S3 index that's used by the rest of the PyTorch ecosystem. If we store all the nightlies there, you only need to push the release packages to PyPI, and we can deprecate use of the `fbgemm-*-nightly` packages entirely. This is what we are doing for torchrec, and should free up space to publish wheels for multiple CUDA versions.

**Comment by spcyppt** [comment]
@osalpekar that sounds great, thank you.

**Comment by colin2328** [comment]
Thanks @osalpekar !

**Comment by shintaro-iwasaki** [comment]
@osalpekar Thank you! We are encountering a CUDA version mismatch issue, so definitely we want to store FBGEMM wheel files built with different CUDA versions soon!

Do you have any ETA in your mind? Can we help/do anything for this?
(cc: @spcyppt and @sryap)

**Comment by osalpekar** [comment]
@shintaro-iwasaki No problem! @spcyppt reached out, and I sent over our [wiki](https://github.com/pytorch/test-infra/wiki/Using-Nova-Reusable-Build-Workflows) on how to migrate to our Nova pipelines, which should fix this issue as well as https://github.com/pytorch/FBGEMM/issues/1920. 

I'm happy to provide any help/support needed for the migration, maybe @spcyppt can give a better estimate for ETA but since we're not starting from scratch I don't think this should take too long?

**Comment by shintaro-iwasaki** [comment]
Oh got it. Then I will ask her. Thank you very much for helping her on this work!

**Comment by spcyppt** [comment]
@shintaro-iwasaki I've started working on it, I should finish by today. Thank you.
@osalpekar thank you so much for your help.

**Comment by spcyppt** [comment]
@henrylhtsang https://github.com/pytorch/FBGEMM/pull/2016

You can now install via
```pip install fbgemm-gpu --index-url https://download.pytorch.org/whl/nightly/cu121```
