### ISSUE TITLE
`.to("meta")` is leaked to the public main branch in the tests.

### ISSUE THREAD

**Issue by liligwu** [pytorch/FBGEMM#1987]
Please check the two tests below.
https://github.com/pytorch/FBGEMM/blob/b42ff6af1ded425e01ce098071aa304983cd9320/fbgemm_gpu/test/permute_pooled_embedding_test.py#L173C49-L173C49
https://github.com/pytorch/FBGEMM/blob/b42ff6af1ded425e01ce098071aa304983cd9320/fbgemm_gpu/test/sparse_ops_test.py#L599

**Comment by q10** [comment]
Not sure if I understand the question correctly, but the `meta` here refers to meta tensors as opposed to Meta (company) -internal code (see https://discuss.pytorch.org/t/a-new-way-to-run-and-support-autograd-with-meta-tensors/160225 for example), so it should not be leaked internal code.  @brad-mengchi, @shintaro-iwasaki, or @sryap could you confirm?

**Comment by shintaro-iwasaki** [comment]
Thanks @q10. Yes it looks quite confusing, but this is a meta tensor.
