### ISSUE TITLE
[Question] 8bit integers and negative numbers

### ISSUE THREAD

**Issue by XapaJIaMnu** [pytorch/FBGEMM#199]
Hey,

I have been reading the code for sparse 8bit gemm: https://github.com/pytorch/FBGEMM/blob/master/test/SpMMI8Test.cc and I have a few questions.

I noticed that `getRandomSparseVector` will only generate positive numbers. Is this because you rely on the `maddubs` instruction? Does it mean that the A matrix can only contain positive numbers?

I noticed this bit in the code:
```c++
for (int i = 0; i < m * k; ++i) {
   aptr[i] &= 0x7F;
 }
```

You avoid large numbers to avoid saturation. Does this mean there is no handling of saturation when it happens?

Thanks,

Nick

**Comment by dskhudia** [comment]
Hi @XapaJIaMnu,

We assume A matrix contains uint8 numbers and B matrix contains int8 numbers. The reason for this is the use of vpmaddubsw instruction. It multiplies signed and unsigned numbers. If you need A numbers to be signed, a preprocessing step to convert them to uint8 can be used.

**Comment by XapaJIaMnu** [comment]
Thank you for the answer @dskhudia ,
`vpmaddubsw` accumulates in 16bit, which is prone to overflowing if the values are not very small. 

How often do you upcast to 32bit?

Cheers,

Nick

**Comment by dskhudia** [comment]
For SoMMI8, we upcast right after vpmaddubsw. https://github.com/pytorch/FBGEMM/blob/master/src/FbgemmSpMM.cc#L573-L581

So the only saturation that can happen is explained here: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cpu/qconv.cpp#L138-L166

**Comment by XapaJIaMnu** [comment]
Thank you for your help!
