### ISSUE TITLE
pytorch master branch is broken

### ISSUE THREAD

**Issue by zhangguanheng66** [pytorch/FBGEMM#213]
Pytorch master branch is broken due to a recent commit. Could anyone revert the update? Thanks.
https://ezyang.github.io/pytorch-ci-hud/build/pytorch-master

https://github.com/pytorch/pytorch/commit/44428d0ee2c1200ed4aad2d960cba0f4b21cddd0

**Comment by jianyuh** [comment]
Will revert. cc @efiks

**Comment by jianyuh** [comment]
closing as https://github.com/pytorch/pytorch/commit/2da3b9a0f64eb16631318945d4a40000db773abd appears to be in the good state now.
