### ISSUE TITLE
Building error after C++20

### ISSUE THREAD

**Issue by zhuhaozhe** [pytorch/FBGEMM#2455]
I faced below error when I follow https://pytorch.org/FBGEMM/fbgemm-development/BuildInstructions.html to build `FBGEMM` after https://github.com/pytorch/FBGEMM/pull/2416.

```
/home/haozhe/upstream/FBGEMM/third_party/asmjit/src/asmjit/arm/../arm/a64instdb_p.h:100:30: error: bitwise operation between different enumeration types ‘asmjit::_abi_1_9::arm::VecV::<unnamed enum>’ and ‘asmjit::_abi_1_9::arm::Vec::SignatureReg’ is deprecated [-Werror=deprecated-enum-enum-conversion]
  100 |   kOp_V2D = VecV::kSignature | Vec::kSignatureElementD
```

I can successfully build at https://github.com/pytorch/FBGEMM/commit/1ad7ab009fab4ee377ddc3bf1729ca8e3cdd4cdd
and failed at 
https://github.com/pytorch/FBGEMM/commit/ab5865a2f9c45cca0b77bf81bd13256a728d5752
My gcc/g++ version.
```
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
```

**Comment by zhuhaozhe** [comment]
On one of my system I can successfully build at https://github.com/pytorch/FBGEMM/commit/ab5865a2f9c45cca0b77bf81bd13256a728d5752 and fail at https://github.com/pytorch/FBGEMM/commit/1ad7ab009fab4ee377ddc3bf1729ca8e3cdd4cdd. On the other system I failed both at https://github.com/pytorch/FBGEMM/commit/ab5865a2f9c45cca0b77bf81bd13256a728d5752 and https://github.com/pytorch/FBGEMM/commit/1ad7ab009fab4ee377ddc3bf1729ca8e3cdd4cdd.

**Comment by q10** [comment]
Hi @zhuhaozhe we will look into this.

**Comment by q10** [comment]
@zhuhaozhe we closed out https://github.com/pytorch/FBGEMM/pull/2461 yesterday, which should fix the issue.  Can you verify you can build FBGEMM under gcc 11+ now?

**Comment by kobalicek** [comment]
This should be also fixed in AsmJit upstream now, so it should not be needed to workaround it.
