### ISSUE TITLE
Build Error On Windows for Shared Library

### ISSUE THREAD

**Issue by shz0116** [pytorch/FBGEMM#266]
I ran into the following linking errors when building the SHARED library on Windows, also on github windows-latest. It could not find the PackMatrix function. But it looks well defined in PackMatrix.cc files. @peterjc123

1. PackAMatrix.cc.obj : error LNK2019: unresolved external symbol "public: __cdecl fbgemm::PackMatrix<class fbgemm::PackAMatrix<unsigned char,int>,unsigned char,int>::PackMatrix<class fbgemm::PackAMatrix<unsigned char,int>,unsigned char,int>(int,int,unsigned char *,int,struct fbgemm::BlockingFactors const *)" (??0?$PackMatrix@V?$PackAMatrix@EH@fbgemm@@EH@fbgemm@@QEAA@HHPEAEHPEBUBlockingFactors@1@@Z) referenced in function "public: __cdecl fbgemm::PackAMatrix<unsigned char,int>::PackAMatrix<unsigned char,int>(enum fbgemm::matrix_op_t,int,int,unsigned char const *,int,unsigned char *,int,struct fbgemm::BlockingFactors const *)" (??0?$PackAMatrix@EH@fbgemm@@QEAA@W4matrix_op_t@1@HHPEBEHPEAEHPEBUBlockingFactors@1@@Z)

2. PackAMatrix.cc.obj : error LNK2019: unresolved external symbol "public: __cdecl fbgemm::PackMatrix<class fbgemm::PackAMatrix<unsigned char,short>,unsigned char,short>::PackMatrix<class fbgemm::PackAMatrix<unsigned char,short>,unsigned char,short>(int,int,unsigned char *,int,struct fbgemm::BlockingFactors const *)" (??0?$PackMatrix@V?$PackAMatrix@EF@fbgemm@@EF@fbgemm@@QEAA@HHPEAEHPEBUBlockingFactors@1@@Z) referenced in function "public: __cdecl fbgemm::PackAMatrix<unsigned char,short>::PackAMatrix<unsigned char,short>(enum fbgemm::matrix_op_t,int,int,unsigned char const *,int,unsigned char *,int,struct fbgemm::BlockingFactors const *)" (??0?$PackAMatrix@EF@fbgemm@@QEAA@W4matrix_op_t@1@HHPEBEHPEAEHPEBUBlockingFactors@1@@Z)

3. PackAWithIm2Col.cc.obj : error LNK2019: unresolved external symbol "public: __cdecl fbgemm::PackMatrix<class fbgemm::PackAWithIm2Col<unsigned char,int,2>,unsigned char,int>::PackMatrix<class fbgemm::PackAWithIm2Col<unsigned char,int,2>,unsigned char,int>(int,int,unsigned char *,int,struct fbgemm::BlockingFactors const *)" (??0?$PackMatrix@V?$PackAWithIm2Col@EH$01@fbgemm@@EH@fbgemm@@QEAA@HHPEAEHPEBUBlockingFactors@1@@Z) referenced in function "public: __cdecl fbgemm::PackAWithIm2Col<unsigned char,int,2>::PackAWithIm2Col<unsigned char,int,2>(struct fbgemm::conv_param_t<2> const &,unsigned char const *,unsigned char *,int,int *,bool,struct fbgemm::BlockingFactors const *)" (??0?$PackAWithIm2Col@EH$01@fbgemm@@QEAA@AEBU?$conv_param_t@$01@1@PEBEPEAEHPEAH_NPEBUBlockingFactors@1@@Z)

4. PackAWithIm2Col.cc.obj : error LNK2019: unresolved external symbol "public: __cdecl fbgemm::PackMatrix<class fbgemm::PackAWithIm2Col<unsigned char,short,2>,unsigned char,short>::PackMatrix<class fbgemm::PackAWithIm2Col<unsigned char,short,2>,unsigned char,short>(int,int,unsigned char *,int,struct fbgemm::BlockingFactors const *)" (??0?$PackMatrix@V?$PackAWithIm2Col@EF$01@fbgemm@@EF@fbgemm@@QEAA@HHPEAEHPEBUBlockingFactors@1@@Z) referenced in function "public: __cdecl fbgemm::PackAWithIm2Col<unsigned char,short,2>::PackAWithIm2Col<unsigned char,short,2>(struct fbgemm::conv_param_t<2> const &,unsigned char const *,unsigned char *,int,int *,bool,struct fbgemm::BlockingFactors const *)" (??0?$PackAWithIm2Col@EF$01@fbgemm@@QEAA@AEBU?$conv_param_t@$01@1@PEBEPEAEHPEAH_NPEBUBlockingFactors@1@@Z)

**Comment by peterjc123** [comment]
What about adding `FBGEMM_API` in https://github.com/pytorch/FBGEMM/blob/master/src/PackMatrix.cc#L17 and https://github.com/pytorch/FBGEMM/blob/master/src/PackMatrix.cc#L32?

**Comment by peterjc123** [comment]
What about adding `FBGEMM_API` in those template class declarations in https://github.com/pytorch/FBGEMM/blob/master/src/PackMatrix.cc?

**Comment by shz0116** [comment]
Since they are only used internally by FBGEMM, adding FBGEMM_API does not help. I am reading 
[https://stackoverflow.com/questions/12573816/what-is-an-undefined-reference-unresolved-external-symbol-error-and-how-do-i-fix](url).
It seems the coding is correct.

**Comment by peterjc123** [comment]
@shz0116  Please see #268.

**Comment by shz0116** [comment]
@peterjc123 Thanks a lot. One thing I am still not clear is that FBGEMM_EXPORT is used to provide visibility to library users so that they can develop codes using exported functions. But,
all the above unresolved references are called from FBGEMM inside. Why they need to be EXPORTED also ?

**Comment by ykim362** [comment]
@shz0116  
1. A function with dllexport and a function with dllimport have different signature. So, they are recognized two different function definitions.
2. In the PackAWithQuantRowOffset.cc file , 'FBGEMM_EXPORTS' is hard coded at the top before fbgemm.h is included. (https://github.com/pytorch/FBGEMM/blob/27cb280170fbf530033c4d0123e063e2f8bb50f3/src/PackAWithQuantRowOffset.cc#L7). This results in '#include 'fbgemm/fbgemm.h' definition uses dllexport.
3. But, 'bench/PackedFloatInOutBenchmark.cc' include fbgemm.h without defining FBGEMM_EXPORTS. In this case, PackedFloatInOutBenchmark looks for dllimport version of PackAWithQuantRowOffset.

By @peterjc123 's PR, the project set FBGEMM_EXPORTS globally. So, there's no mismatch any more.

Also, please see this. In MSVC, if a class is declared with 'dllexport', all the members are automatically exported with dllexport.
https://docs.microsoft.com/en-us/cpp/cpp/using-dllimport-and-dllexport-in-cpp-classes?view=vs-2019

Hope this helps.

P.S. It would be better to remove all FBGEMM_EXPORTS definitions from the .cc files and fully controlled by cmake files. I wonder why they are all added in the .cc files.
