### ISSUE TITLE
Conv1D via gemm is slow?

### ISSUE THREAD

**Issue by gibiansky** [pytorch/FBGEMM#292]
I am trying to use FBGEMM to implement a 1D convolution. I am doing via an im2col method, in which I copy convert a `[batch, timesteps, input_channels]` tensor into a `[batch * timesteps, conv_width * input_channels]` tensor and then multiply by the B-matrix of shape `[conv_input * input_channels, output_channels]`. I have also noticed that `wav2letter` takes the same approach in their source code.

I am using `ReQuantizeForFloat` as the output pipeline and doing the multiplication in 8-bit integer arithmetic with 32-bit accumulation.

My benchmarks show that, for large numbers of timesteps, this is significantly *slower* than MKL (operating in fp32). I've reduced my issue to a small benchmark that only tests the gemm with a large batch size (on the order of 500 to 5000).

Is this the expected behaviour? Can I do something differently to get good performance from FBGEMM gemms on the sizes I'm working with? (`5000x256 * 256x256`, for example.) Thanks.

**Comment by gibiansky** [comment]
Here's the FBGEMM code. 

```
// Setup below is not timed in benchmark
int32_t Aint8_zero_point = 43;
float Aint8_scale = 0.11;

int32_t Bint8_zero_point = -23;
float Bint8_scale = 2.0;

int ncols_per_quant_group = out_size;
int32_t* col_offsets = new int32_t[out_size];
col_offsets_with_zero_pt_s8acc32_ref(
    in_size, out_size, out_size, mat_int8, &Bint8_zero_point, col_offsets,
    ncols_per_quant_group);

DoNothing<float, float> doNothingObj{};
PackBMatrix<int8_t, int32_t> packedBN(
    matrix_op_t::NoTranspose, in_size, out_size, mat_int8, out_size, nullptr, 1);

// Below is benchmarked
PackAWithQuantRowOffset<uint8_t, int32_t> packAN(
    matrix_op_t::NoTranspose, batch_size, in_size, vec, in_size);
ReQuantizeForFloat<false> outputProcObj(
    doNothingObj, Aint8_scale, &Bint8_scale, Aint8_zero_point, &Bint8_zero_point,
    packAN.getRowOffsetBuffer(), col_offsets, nullptr, out_size, 1);
fbgemmPacked(packAN, packedBN, out_fp32, buffer_int32, out_size, outputProcObj, 0, 1);
```

**Comment by dskhudia** [comment]
Hi @gibiansky,
 
Thanks for reporting this. If I am reading this correctly, we don't get any speedups for M > 256 for int8 gemms. I will take a look at this and report back soon.

**Comment by gibiansky** [comment]
That's correct. Please let me know if I can provide any more information that would be useful for investigating this. I can (if it turns out to be helpful) provide the complete source code to the binary that provided the results above as well as processor specs (it's an AWS box with AVX2 but not AVX-512). Thanks!

**Comment by dskhudia** [comment]
Which version of MKL are you using?

**Comment by gibiansky** [comment]
It's version 2018.1.163.

**Comment by dskhudia** [comment]
Thanks @gibiansky, 

I ran the floatinout benchmark (https://github.com/pytorch/FBGEMM/blob/master/bench/PackedFloatInOutBenchmark.cc) by changing the shapes to (https://github.com/pytorch/FBGEMM/blob/master/bench/PackedFloatInOutBenchmark.cc#L35-L68) you are interested in . This benchmark is doing exactly what you are trying to accomplish and I see the following results on a SKL machine. Unfortunately I don't have access to an AVX2 machine currently but I expect similar behavior.
```
WARNING: the timer may be inaccurate when used by multiple threads.
     M,      N,      K,         Packing (ms),          Kernel (ms),  Postprocessing (ms),           Total (ms),                 Type,  GOPs
     1,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_FP32,   2.3
     1,    256,    256,                0.004,                0.007,                0.001,                0.016,      FBGEMM_i8_acc32,   7.6

     2,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_FP32,   4.6
     2,    256,    256,                0.004,                0.008,                0.002,                0.018,      FBGEMM_i8_acc32,  13.6

     4,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_FP32,   9.3
     4,    256,    256,                0.004,                0.015,                0.003,                0.026,      FBGEMM_i8_acc32,  19.0

     8,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_FP32,  19.2
     8,    256,    256,                0.007,                0.040,                0.004,                0.056,      FBGEMM_i8_acc32,  18.3

    32,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_FP32,  47.5
    32,    256,    256,                0.023,                0.065,                0.006,                0.098,      FBGEMM_i8_acc32,  42.3

   256,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_FP32,  86.9
   256,    256,    256,                0.067,                0.260,                0.042,                0.377,      FBGEMM_i8_acc32,  88.8

   512,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_FP32,  97.5
   512,    256,    256,                0.107,                0.476,                0.083,                0.681,      FBGEMM_i8_acc32,  98.4

  1024,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_FP32, 103.6
  1024,    256,    256,                0.182,                0.911,                0.165,                1.284,      FBGEMM_i8_acc32, 104.5

  2048,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_FP32, 103.1
  2048,    256,    256,                0.355,                1.793,                0.333,                2.527,      FBGEMM_i8_acc32, 106.2

  4096,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_FP32, 106.2
  4096,    256,    256,                0.720,                3.519,                0.657,                4.983,      FBGEMM_i8_acc32, 107.7
 ```

The performance is similar to MKL_FP32 ( I have MKL 2017.0 Update 3 Product build 20170413). However if I run a similar benchmark (https://github.com/pytorch/FBGEMM/blob/master/bench/PackedRequantizeAcc32Benchmark.cc) that takes in uint8 input and outputs uint8 I see the following results. 

```
WARNING: the timer may be inaccurate when used by multiple threads.
     M,      N,      K,         Packing (ms),          Kernel (ms),  Postprocessing (ms),           Total (ms),                 Type,  GOPs
     1,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_fp32,   2.3
     1,    256,    256,                0.002,                0.008,                0.001,                0.017,      FBGEMM_i8_acc32,   5.6

     2,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_fp32,   5.1
     2,    256,    256,                0.002,                0.011,                0.002,                0.021,      FBGEMM_i8_acc32,   9.4

     4,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_fp32,   9.6
     4,    256,    256,                0.002,                0.016,                0.002,                0.025,      FBGEMM_i8_acc32,  14.2

     8,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_fp32,  17.0
     8,    256,    256,                0.002,                0.040,                0.003,                0.050,      FBGEMM_i8_acc32,  17.1

    32,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_fp32,  46.9
    32,    256,    256,                0.005,                0.067,                0.005,                0.081,      FBGEMM_i8_acc32,  46.4

   256,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_fp32,  81.9
   256,    256,    256,                0.016,                0.254,                0.028,                0.309,      FBGEMM_i8_acc32, 105.7

   512,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_fp32,  91.1
   512,    256,    256,                0.024,                0.470,                0.057,                0.565,      FBGEMM_i8_acc32, 117.2

  1024,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_fp32,  98.2
  1024,    256,    256,                0.040,                0.878,                0.105,                1.047,      FBGEMM_i8_acc32, 127.2

  2048,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_fp32, 101.3
  2048,    256,    256,                0.075,                1.716,                0.210,                2.044,      FBGEMM_i8_acc32, 130.8

  4096,    256,    256,                0.000,                0.000,                0.000,                0.000,             MKL_fp32, 103.9
  4096,    256,    256,                0.144,                3.383,                0.414,                4.020,      FBGEMM_i8_acc32, 133.3
```

From the comparison, we can see that for larger sizes in your use case the time in packing (which also needs to do fp32 => uint8 conversion) as well as postprocessing has increased even though kernel time is approximately the same. Any reason you want to have fp32 input/output and still want to use int8 compute?

**Comment by gibiansky** [comment]
I can run this benchmark on my machine as well. It's surprising that we're getting such different results; at the largest size (4096x256x256 I'm getting almost 2X _slower_ than MKL2018). 

What is an SKL machine?

We were using FP32 input/output so as to not quantize the bias and reduce quantization error (since IIUC the int32->fp32 conversion should have less quantization error than the int32->int8 requantization). We may do the extra work to get rid of the intermediate FP32 representation if it significantly improves performance though.

**Comment by dskhudia** [comment]
> I can run this benchmark on my machine as well.
Yes. Please see the results of this benchmark. 

> What is an SKL machine?
https://ark.intel.com/content/www/us/en/ark/products/120476/intel-xeon-gold-6138-processor-27-5m-cache-2-00-ghz.html

FBGEMM does support keeping bias in fp32 (and dynamically quantizing bias during postprocessing). Using something similar to PackedRequantizeAcc32Benchmark.cc with float bias might be better from the performance point of view. (Example: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cpu/qlinear.cpp#L84)

**Comment by gibiansky** [comment]
Ah SKL = skylake. 

```
    M,     N,     K,             Type,  GOPS
    1,   256,   256,         MKL_FP32,   2.4
    1,   256,   256,  FBGEMM_i8_acc32,   3.6

    2,   256,   256,         MKL_FP32,   3.7
    2,   256,   256,  FBGEMM_i8_acc32,   6.9

    4,   256,   256,         MKL_FP32,   7.3
    4,   256,   256,  FBGEMM_i8_acc32,  13.2

    8,   256,   256,         MKL_FP32,  12.1
    8,   256,   256,  FBGEMM_i8_acc32,  23.0

   16,   256,   256,         MKL_FP32,  20.6
   16,   256,   256,  FBGEMM_i8_acc32,  34.5

   32,   256,   256,         MKL_FP32,  32.3
   32,   256,   256,  FBGEMM_i8_acc32,  44.0

   64,   256,   256,         MKL_FP32,  41.0
   64,   256,   256,  FBGEMM_i8_acc32,  50.2

  128,   256,   256,         MKL_FP32,  50.4
  128,   256,   256,  FBGEMM_i8_acc32,  57.5

  256,   256,   256,         MKL_FP32,  57.3
  256,   256,   256,  FBGEMM_i8_acc32,  63.8

  512,   256,   256,         MKL_FP32,  50.4
  512,   256,   256,  FBGEMM_i8_acc32,  66.0

 1024,   256,   256,         MKL_FP32,  63.4
 1024,   256,   256,  FBGEMM_i8_acc32,  66.9

 2048,   256,   256,         MKL_FP32,  68.9
 2048,   256,   256,  FBGEMM_i8_acc32,  66.1

 4096,   256,   256,         MKL_FP32,  69.6
 4096,   256,   256,  FBGEMM_i8_acc32,  67.3
```

I guess we're getting similar results; using FBGEMM's int8 is competitive with MKL for large M but unless you switch to keeping everything in int8 you get no speedups. If you _do_ switch to int8 you get at most a 1.3X speedup (from the GOPs values in your benchmark).

Thanks.

**Comment by dskhudia** [comment]
Yes. That's right. 1.3x is machine limitation. Even though with int8 data we can work on 4x more data at a time using vector instructions but we need three instructions to perform the work (vpmaddubsw, vpmaddwd and vpaddd) for a single multiply+add for int8 values. Newer processors (Cooper lake onwards) can do all this work using a single instruction so can be potentially 4x faster wrt fp32.

**Comment by gibiansky** [comment]
Got it, thank you. I was not sure whether this was an inherent limitation (as you described) or just an unhandled use-case. I guess that at these large batch values the compute dominates and so you don't get the 4X speedup you see at M=1 for large N and K values. This makes sense, and since it seems like this is pretty much the expected behaviour, it seems like this issue can be closed.

Thanks for putting in https://github.com/pytorch/FBGEMM/commit/86b8098f1b169699f879ce662e63265514d5c426 by the way, I hit the same issue in running this benchmark and trying to get results formatted like yours.
