### ISSUE TITLE
fbgemm_gpu_py.so: undefined symbol: _ZNK3c105Error4whatEv

### ISSUE THREAD

**Issue by zhaozheng09** [pytorch/FBGEMM#2938]
<img width="1757" alt="image" src="https://github.com/user-attachments/assets/964234e9-2b07-41a9-a98d-c51a6d7b88ec">

**Comment by spcyppt** [comment]
Hi, could you share if you're using which torch and fbgemm versions and commands used for the installation?

**Comment by zhaozheng09** [comment]
> Hi @zhaozheng09 , could you share if you're using which torch and fbgemm versions and commands used for the installation?

torchrec==0.8.0 fbgemm==0.8.0

**Comment by spcyppt** [comment]
@zhaozheng09 thank you for the information. I assume you use torch==0.8.0?

1. Could you run `python -c "import torch; print(torch.__version__, torch.version.cuda); "` and let me know the results? Just to confirm torch cuda version. 
2. Are you able to `import fbgemm_gpu` at all? Please run `python -c "import torch; import fbgemm_gpu; print(fbgemm_gpu.__version__)"`

**Comment by zhaozheng09** [comment]
I update cuda11.4->cuda12.1 it's ok .
