### ISSUE TITLE
macos install fbgemm error. 

### ISSUE THREAD

**Issue by zhaozheng09** [pytorch/FBGEMM#2945]
<img width="1919" alt="image" src="https://github.com/user-attachments/assets/c9a4f45e-b72e-40df-9416-6299e9bf0ac4">

**Comment by zhaozheng09** [comment]
```pip3 install torchrec numpy==1.26.4 --break-system-packages``` success;
```make html``` error and report OSError: dlopen(/usr/local/lib/python3.12/site-packages/fbgemm_gpu/fbgemm_gpu_py.so, 0x0006): tried: '/usr/local/lib/python3.12/site-packages/fbgemm_gpu/fbgemm_gpu_py.so' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/python3.12/site-packages/fbgemm_gpu/fbgemm_gpu_py.so' (no such file), '/usr/local/lib/python3.12/site-packages/fbgemm_gpu/fbgemm_gpu_py.so' (not a mach-o file)

**Comment by spcyppt** [comment]
Could you share pytorch version? `python -c "import torch; print(torch.__version__, torch.version.cuda); "`. Are you able to `python -c "import torch; import fbgemm_gpu; print(fbgemm_gpu.__version__)`?

**Comment by q10** [comment]
Unfortunately, MacOS is not a supported platform for FBGEMM_GPU at the moment.

**Comment by zhaozheng09** [comment]
好吧。it's ok ~
