### ISSUE TITLE
fail to compile version v0.8.0 on cuda 12.4

### ISSUE THREAD

**Issue by gouchangjiang** [pytorch/FBGEMM#2950]
Following the instructions from [BuildInstructions](https://pytorch.org/FBGEMM/fbgemm_gpu-development/BuildInstructions.html), an internal error of nvcc raises. The CUDA/GCC I am using are 12.4.0, 10.4.0 respectively.

<img width="1589" alt="fbgemm_cuda124" src="https://github.com/user-attachments/assets/783f3a20-febf-4062-b64a-e6962a5e1fbe">

**Comment by gouchangjiang** [comment]
By the way, v0.7.0 works well with cuda 12.4

**Comment by q10** [comment]
Hi @gouchangjiang, I'm unable to reproduce the segfault that you've reported.  This is what I ran on my terminal:

```
git clone https://github.com/pytorch/FBGEMM.git --branch v0.8.0
cd FBGEMM && . .github/scripts/setup_env.bash

setup_miniconda $HOME/miniconda
test_setup_conda_environment build_env gcc 3.12 pip nightly cuda 12.4.0

test_fbgemm_gpu_build_and_install build_env cuda
```

Could you try these commands and let me know if you still run into the issue?

**Comment by gouchangjiang** [comment]
Thank you very much. Your scripts work well on my machine. So I missed something, I guess.
