### ISSUE TITLE
Building Cython bindings and a Python package

### ISSUE THREAD

**Issue by honnibal** [pytorch/FBGEMM#3]
Thanks for open-sourcing this! I've spent a tonne of time trying to get a decent gemm solution for [spaCy](https://github.com/explosion/spaCy) over the last two years. I won't even list the number of things I've tried and yaks I've shaved in this quest. The current plan is to package [Blis](https://github.com/explosion/cython-blis), but the API and support for low precision maths is really appealing here. FBGEMM does more of what I need and none of the things I don't, so I'm interested in seeing whether we could adopt it.

The holy grail for me is a Python package that ships the source code of a C extension, along with Cython bindings. The Python package's setup.py compiles the extension, and statically links the C++ dependency into it. At the same time, binary wheel files should be available that do dynamic architecture detection.

I understand it's probably a long road to get this to work, and might not be viable. I do believe it's worth trying, though. If we can just get a decent GEMM package for Python, with C-level bindings exposed, the ML community will benefit enormously. The current GEMM problems are really bad. Currently, it's super common for people to end up with numpy installations that call into Prescott-targeted kernels, cratering CPU performance. I really believe this problem is costing labs everywhere a fortune in compute costs, because folks are moving workloads to GPU that they could execute much more cheaply on CPU if they only had their systems properly configured.

Some questions:

* Does FBGEMM support dynamic architecture detection? Like, can I compile a binary on a server with avx-512 instructions, and run it on another server that only has avx2?

* What's the prognosis for future Windows support look like? I think requiring LLVM is reasonable, to avoid the weirdness of MSVC. I think this should mostly make it about the build system and threading library? Note that currently, support for Windows Subsystem for Linux is impossible, as WSL doesn't expose avx2 instructions: https://github.com/Microsoft/WSL/issues/2234 .

**Comment by dskhudia** [comment]
Hi @honnibal ,

Thanks for you interest in FBGEMM!

For Python, we do have some plans so stay tuned for that. 

FBGEMM supports dynamic architecture detection of AVX2 and AVX512 during the runtime. As you mentioned, you can compile a binary (using our CMAKE building file) on a server (which should have a GCC compiler supporting -mavx2 and -mavx512f), and run it on another server that only has AVX2. However, it is only designed for avx2 and higher instructions sets. There is no support for pre-avx2 CPUs. 

There are two reasons why we can compile with avx512 and run on a server with only avx2:
1. The microkernel part for matrix-shape specific vectorized code is dynamically generated by JIT (asmjit). So the AVX2 and AVX512 code for the microkernel is generated according to the runtime detection of the architecture.
2. For architecture-dependent intrinsic based code (e.g., transpose routines in src/Utils.cc and src/Utils_avx512.cc), we split it into separate files, compile them with separate flags, and finally link them into one binary file. During the runtime, we will do dynamic runtime detection and choose the right path.

In future, we want to support Windows. But at the moment it's not a priority. Thanks for pointing out that WSL doesn’t expose AVX2 instructions.

**Comment by honnibal** [comment]
Sounds great, thanks! Actually another question: does the library do multi-threading, and is it easy to disable it at runtime? Because inference is embarrassingly parallel, I find I pretty much never want the matrix multiplications to be multi-threaded.

Also, a small suggestion when you come to look at the Python bindings: It would be great if you also exposed a Cython-level interface, ideally colored `nogil`. This makes the library much more useful. If the Cython interface requires a memoryview or a numpy array, then if I'm holding a pointer, I have to acquire the GIL just to make the matrix multiplication.

In my blis wrapper, I'm using fused types to support both memoryviews and pointers in the same function. You can see an example here: https://github.com/explosion/cython-blis/blob/master/blis/cy.pyx The dispatch is determined at compile time, so there's no overhead. We can also support multiple types this way, e.g. a buffer of int8, a buffer of float16, etc. I'd be happy to help with this when the time comes.

**Comment by jianyuh** [comment]
Hi Matthew @honnibal,

Currently FBGEMM only supports single thread, so you don’t need to handle the hassle of disabling multi-threading. As you mentioned, for the inference, the parallelism is provided through the upper level deep learning library such as Caffe2 (e.g., check https://github.com/pytorch/pytorch/tree/master/caffe2/quantization/server, which actually uses FBGEMM).

As a caveat, we are also working on a multi-thread version. You may observe the interface for the function ```fbgemmPacked``` by design has already reserved the arguments of ```thread_id``` and ```num_threads```, although both arguments are not used inside the implementations.

The current workflow for the Python bindings on FBGEMM is through the upper level deep learning library (PyTorch -> Caffe2 -> FBGEMM), although we don’t have a way to call FBGEMM directly with Python. Glad to hear that you are willing to help us with the Cython-level interface! We will keep that in mind when the time comes! 

@dskhudia @jspark1105: Feel free to chime in if you've got something to add.
