### ISSUE TITLE
[Question] using FBGEMM (int8 GEMM) in a multi-threaded application

### ISSUE THREAD

**Issue by ykim362** [pytorch/FBGEMM#374]
Hi,
I have a question about the usage of FBGEMM in a multi-threaded program.
In my test environment, I have 24 cores CPU and 20 independent threads calling FBGEMM (int8 GEMM). All the threads are doing independent jobs, so there's no parallelism for one fbgemm call.  https://github.com/marian-nmt/marian-dev/blob/master/src/tensors/cpu/fbgemm/packed_gemm.cpp#L614

In a heavy load situation, I'd expect higher than 2000% cpu utilization, but the cpu utilization is always less than 250% (seems only one thread is using fbgemm). Have you had this kind of problem before?
(FYI, when I use fp16 fbgemm, I don't have this issue. The cpu utilization is higher than 2000%.)
https://github.com/marian-nmt/marian-dev/blob/master/src/tensors/cpu/fbgemm/packed_gemm.cpp#L516

Thank you in advance!

**Comment by jianyuh** [comment]
Hi @ykim362,

Want to understand your use case: 
> I have 24 cores CPU and 20 independent threads calling FBGEMM (int8 GEMM). All the threads are doing independent jobs, so there's no parallelism for one fbgemm call.

Are you running 20 instances (processes) where each instance calls FBGEMM independently (no communications), or 1 instance with 20 threads calling multi-threaded FBGEMM?

Looking at your code (https://github.com/marian-nmt/marian-dev/blob/master/src/tensors/cpu/fbgemm/packed_gemm.cpp#L614), the tid and num_threads are passed as 0 and 1 in int8 GEMM, so this is the single-thread usage. For FP16 FBGEMM (https://github.com/marian-nmt/marian-dev/blob/master/src/tensors/cpu/fbgemm/packed_gemm.cpp#L516), you are passing the tid and num_threads, though.

**Comment by ykim362** [comment]
Thanks, @jianyuh .

Yes, I am running 20 instances (20 threads in one process) and each instance calls FBGEMM independently without communications. 

For fp16 FBGEMM call, even if the parallelism is enabled, openmp is disabled in all my use cases. So, they are always 0 and 1.

**Comment by dskhudia** [comment]
If each instance is calling FBGEMM independently without communications then I would expect it to have 2000% cpu utilization for your case. The only sharing in FBGEMM under such a scenario is the sharing of code generated at runtime. Are you building with C++11 or C++14? With C++11, we saw contention on reading the shared code cache across threads and for C++14 it was fixed using read-write locks. https://github.com/pytorch/FBGEMM/commit/35e486b706abd4d575ae9b7aaf090002aa78551e

**Comment by ykim362** [comment]
Thanks so much, @jianyuh  and @dskhudia !
I found that there's a thread contention problem in my use case.

This is caused by allocating and de-allocating `pmat` buffer dynamically in `PackAMatrix`. It causes a contention problem for the heap access when the number of concurrent access increases.
So, by allocating one buffer and keep re-using it, I could resolve the problem.
In my case, I didn't see a contention problem for the code cache.
