### ISSUE TITLE
[Questions] Why doesn't PyTorch use accumulation int16_t mode

### ISSUE THREAD

**Issue by yufenglee** [pytorch/FBGEMM#376]
FBGEMM is faster with accumulation int16_t. Why don't I see PyTorch use this mode?

**Comment by jianyuh** [comment]
In Caffe2, the int16_t accumulation of FBGEMM int8 GEMM is used for fully connected op: https://github.com/pytorch/pytorch/blob/master/caffe2/quantization/server/fully_connected_dnnlowp_acc16_op.cc

In PyTorch, we currently only support int32_t accumulation. One drawback of int16_t accumulation is that it usually lead to frequent overflow/saturation.  We can normally avoid this by using outlier-aware quantization, which requires some additional overhead.

On the Broadwell machines, we usually see int8 GEMM with int16_t accumulation + outlier-aware quantization is faster than int8 GEMM with int32_t accumulation. However, on the Skylake machines, we didn't observe too much performance benefit by using int16_t accumulation for some special shapes we apply the quantization.

**Comment by yufenglee** [comment]
Thanks for your clarification.
