### ISSUE TITLE
[ Question ] Leveraging Int16 Accumulation Type for convolution 

### ISSUE THREAD

**Issue by arunnura123** [pytorch/FBGEMM#417]
Hi ,

  I use pytorch vision to run INT8 optimized resnet on AVX2 machine. The code path uses "optimized_conv_t::im2col" .
 It looks accumulation type for PackWeightsForConv is set to INT32 . Kindly let me know  if there is a  way to set Accumulation type to INT16 .  My understanding is that INT16 accumulation can leverage ( MR*NR ) = 12 * 16 registers while that gets limited to 6 * 16 registers with INT32 per the packing traits of FBGEMM. 

   Is there a way to accumulate in INT16  ( INT8 weights and INT8 inputs ) for AVX2 path and requantize the accumulated
outputs as INT32. 

  Can I change the default accumulation to INT16 by modifying  "include/fbgemm/Fbgemm.h" and why INT32 is set as default.

Thanks,
Arun

**Comment by dskhudia** [comment]
@arunnura123,

For PyTorch, we have only added support for INT32 accumulation. There are multiple reasons for it. 
1) Accumulations into INT16 will saturate early so it may lead to accuracy degradations. To recover the accuracy degradations, we need to specify outliers (bigger weights that cause saturations early) and compute sparse-dense matrix-matrix multiplication for these outliers to compensate for the lost accuracy. Overall, this makes it very complicated for marginal gains (See #2 below)
2) This optimization was mostly beneficial for Intel Broadwell cpus where it resulted in 2x performance gains wrt int32 accumulations. For current (Intel Skylake), performance gains are marginal 10-30% and Intel (Cascase Lake/Cooper Lake) onwards there is no point in using acc16 as VNNI by default does int32 accumulations. 

If you want to use it in PyTorch, you will need to hack it in qconv operator implementation and some hacking will be needed from FBGEMM side as well. We do not have any plan to support int16 accumulations in PyTorch. I would recommend to use int32 accumulations.

**Comment by arunnura123** [comment]
Thanks so much for the prompt response and suggestions.
