### ISSUE TITLE
[Question] offline packed memory

### ISSUE THREAD

**Issue by ykim362** [pytorch/FBGEMM#427]
Hi,
I would like to skip pack() in PackBMatrix() in my use case. I pack memory offline and keep raw memory in another place. For a workaround, I created another constructor in my fork of FBGEMM. https://github.com/marian-nmt/FBGEMM/blob/master/src/PackBMatrix.cc#L241 (This is one of the main reasons Marian maintains a separate fork of FBGEMM)
Would there be any way to create PackBMatrix() without calling pack(), or would you consider to merge if I submit a PR for this?
Thanks!

**Comment by dskhudia** [comment]
Hi @ykim362, 

I think if we create another constructor for PackBMatrix which creates and initializes the packed buffer properly (And other variables), it should work. Please create a PR and I can merge it.

**Comment by ykim362** [comment]
Thank you, @dskhudia !
We've been using it this way for a long time and it's been working well. With this, Marian might be able to directly use the public FBGEMM. I will created a PR, soon.

**Comment by omegacoleman** [comment]
I stumbled upon the same problem and came up with a solution with minimal changes to upstream: #4665
