### ISSUE TITLE
Add stdexcept to  include/fbgemm/FbgemmPackMatrixB.h

### ISSUE THREAD

**Issue by happydig** [pytorch/FBGEMM#444]
Compiled on Fedora 32 failed. I added #include <stdexcept> to include/fbgemm/FbgemmPackMatrixB.h to fix it.

Thanks.

**Comment by dskhudia** [comment]
Hi @happydig, 

did you create a PR?

**Comment by happydig** [comment]
> Hi @happydig,
> 
> did you create a PR?

It was fixed 4 days ago.
