### ISSUE TITLE
Error when compiling for shared target

### ISSUE THREAD

**Issue by nihiluis** [pytorch/FBGEMM#461]
Hi, I'm looking to build a so library which depends on Wav2Letter which depends on FBGEMM. For some FFI usage. I'm receiving some error.

I tried enabling -fPIC but can't figure out how to make the linking work. Can I circumvent this?

```
/usr/bin/ld: 3rdparty/wav2letter/inference/inference/module/fbgemm/src/fbgemm/libfbgemm.a(FbgemmFP16.cc.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
3rdparty/wav2letter/inference/inference/module/fbgemm/src/fbgemm/libfbgemm.a: error adding symbols: Bad value
```

Here I tried to manipulate the CMakeLists.txt of fbgemm. No change though. This is the relevant extract.
```
project(fbgemm VERSION 0.1 LANGUAGES CXX C)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")

set(FBGEMM_LIBRARY_TYPE "shared")
```

This is my cmake part

```
add_library(${project_name}_api
  SHARED
  src/api.cpp
  src/api.h
)

set_target_properties(fbgemm PROPERTIES POSITION_INDEPENDENT_CODE ON)
set_target_properties(streaming_inference_modules_nn_impl PROPERTIES POSITION_INDEPENDENT_CODE ON)
set_target_properties(streaming_inference_modules_nn_backend PROPERTIES POSITION_INDEPENDENT_CODE ON)
set_target_properties(${project_name} PROPERTIES POSITION_INDEPENDENT_CODE ON)
set_target_properties(${project_name}_api PROPERTIES POSITION_INDEPENDENT_CODE ON)
```

**Comment by dskhudia** [comment]
Hi @nihiluis ,

I tried building it on mac with 

mkdir build && cd build
cmake -DFBGEMM_LIBRARY_TYPE=shared ..

Shared lib libfbgemm.dylib is built fine. Let me try on linux and will comment again.

**Comment by dskhudia** [comment]
It also builds fine on a linux system and creates libfbgemm.so 

May be the issue is with when you build it as cmake dependency.

**Comment by nihiluis** [comment]
It seems that Wav2letter ignores the libfbgemm.so. The building works fine for me as well.
