### ISSUE TITLE
error: 'posix_memalign' was not declared in this scope

### ISSUE THREAD

**Issue by KOLANICH** [pytorch/FBGEMM#5]
>../third_party/fbgemm/include/fbgemm/Fbgemm.h:1012:7: error: 'posix_memalign' was not declared in this scope
   if (posix_memalign(&aligned_mem, __align, __size))

when built with MinGW.

The solution: https://stackoverflow.com/questions/10862121/undefined-reference-to-posix-memalign-using-mingw32

**Comment by dskhudia** [comment]
Hi @KOLANICH ,

We will get to it but once we our priority queue clears out a bit. 

Thanks
Daya

**Comment by KOLANICH** [comment]
Thank you for informing me.
