### ISSUE TITLE
Get CMake Error when trying to generate doc using sphinx.

### ISSUE THREAD

**Issue by ngsiming** [pytorch/FBGEMM#532]
Hello! I'm trying to generate the docs of `FBGEMM` and get some errors.

I modify the CMakeList.txt to turn the `FBGEMM_BUILD_DOCS` ON(by moditify `option(FBGEMM_BUILD_DOCS "Build fbgemm documentation" OFF)` to `option(FBGEMM_BUILD_DOCS "Build fbgemm documentation" ON)`) and do `cmake ..`.

But it reports CMake Error like this:
`CMake Error at docs/CMakeLists.txt:2 (find_package):`
 ` By not providing "FindSphinx.cmake" in CMAKE_MODULE_PATH this project has`
`  asked CMake to find a package configuration file provided by "Sphinx", but`
`  CMake did not find one.`
`...`

I try to add the path where the Sphinx is installed like this 
`cmake .. -DCMAKE_PREFIX_PATH=/usr/lib/python3/dist-packages/sphinx`
but I get the same error.

Is there something I did wrong?

**Comment by jianyuh** [comment]
https://github.com/pytorch/FBGEMM/pull/536 should address the issue.

**Comment by ngsiming** [comment]
It works well now. Thanks.
