### ISSUE TITLE
Is it possible to generate SPMDM kernels with asmjit?

### ISSUE THREAD

**Issue by YangWang92** [pytorch/FBGEMM#540]
Hi all, 
Thanks for sharing such a high-performance GEMM library.

After reading through source codes,  I found that only U8S8S32AC* kernels are generated from asmjit. 
Is it possible to port SpMDM codes to asmjit? I'm tring to optimzie SpMDM by myself.

Thanks!
Yang

**Comment by dskhudia** [comment]
Hi Yang, 

We have high-performance spmdm code for AVX512 and above x86-64 ISA in https://github.com/pytorch/FBGEMM/blob/master/src/FbgemmSparseDenseAvx512.cc (fp32) and https://github.com/pytorch/FBGEMM/blob/master/src/FbgemmSparseDenseInt8Avx512.cc (int8). Examples to use these apis are in https://github.com/pytorch/FBGEMM/blob/master/bench/SparseDenseMMFP32Benchmark.cc and https://github.com/pytorch/FBGEMM/blob/master/bench/SparseDenseMMInt8Benchmark.cc  

Thanks
Daya
