### ISSUE TITLE
Is there anything I should be careful of when creating a pointer pointing to `PackBMatrix` and passing it as a parameter?

### ISSUE THREAD

**Issue by ngsiming** [pytorch/FBGEMM#545]
Hello! I am using FBGEMM in my project. I create a pointer pointing to `PackBMatrix<int8_t>` and pass it to a function as parameters. Segmentation fault occurs when `fbgemmPacked()` is called. I think may be something goes wrong when creating the pointer and passing parameters. Is there something I should be careful of when creating a pointer to `PackBMatrix` and using it as parameter? Following is a piece of my code. I will be very grateful for your help!

`PackBMatrix<int8_t> *packedBN=nullptr;`
` `
`packedBN = new PackBMatrix<int8_t>(`
` transpose ? matrix_op_t::Transpose : matrix_op_t::NoTranspose,`
` nrow, ncol, quantized, transpose ? nrow : ncol, packedbuf, 1, params);`
` `
`...`
` void fbgemmPacked8Gemm(`
`...`
`//PackBMatrix as parameter`
` PackBMatrix<int8_t>* packedBN,`
`...`
`){`
`...`
` // gemm computation`
`    fbgemmPacked(packAN, *packedBN, (float*)C.data, (int32_t*)C.data, (int32_t) n, outputProcObj, 0, 1, params);`
`...`
`}`
` `
`...`
`fbgemmPacked8Gemm(`
`...`
`packedBN,`
`...`
`);`

**Comment by dskhudia** [comment]
How do you allocate packedbuf? It should be sufficiently big (https://github.com/pytorch/FBGEMM/blob/master/src/PackBMatrix.cc#L245-L248). Alternative to this is to pass packedbuf argument as nullptr and let PackBmatrix manage the memory allocation for packed buffer. Also you don't need to pass params argument unless you want to. 

If this still doesn't help, could you run this in debug mode with gdb and post a stack trace?

**Comment by ngsiming** [comment]
> How do you allocate packedbuf? It should be sufficiently big (https://github.com/pytorch/FBGEMM/blob/master/src/PackBMatrix.cc#L245-L248). Alternative to this is to pass packedbuf argument as nullptr and let PackBmatrix manage the memory allocation for packed buffer. Also you don't need to pass params argument unless you want to.
> 
> If this still doesn't help, could you run this in debug mode with gdb and post a stack trace?

@dskhudia Thanks a lot! I found that it was indeed caused by the incorrect use of packedbuf. I passed packedbuf as argument nullptr and now it works well. Very grateful to you for your help!
