### ISSUE TITLE
Test failures: RowWiseSparseAdagradFusedTest, SparseAdagradTest

### ISSUE THREAD

**Issue by adamjstewart** [pytorch/FBGEMM#631]
When testing my FBGEMM installation I noticed the following test failures:
```console
$ make -j12 test
...
The following tests FAILED:
	 16 - RowWiseSparseAdagradFusedTest (Failed)
	 17 - SparseAdagradTest (Failed)
Errors while running CTest
Output from these tests are in: /tmp/t-astewart/spack-stage/spack-stage-fbgemm-master-kqngcydkqhc6umwgpjq2xs55rawby5es/spack-build-kqngcyd/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
Makefile:138: recipe for target 'test' failed
make: *** [test] Error 8
```
I'm not passing any special customizations to the build. Here is the build log:

* [spack-build-out.txt](https://github.com/pytorch/FBGEMM/files/6652172/spack-build-out.txt)

Unfortunately, `LastTest.log` is too large to upload to GitHub. This occurs with the master version of FBGEMM built with GCC 7.3.0 on Ubuntu 18.04.

@dskhudia

**Comment by dskhudia** [comment]
Thanks for creating this issue. We will take a look.

**Comment by adamjstewart** [comment]
On macOS 10.15.7 and Apple Clang 12.0.0 and commit 7794b2950b35ddfa7426091e7fb2f991b1407557 (2021-05-10), I see even more failures:
```console
$ ninja -j4 test
...
The following tests FAILED:
	  1 - Bfloat16ConvertTest (ILLEGAL)
	  5 - FP16Test (ILLEGAL)
	  6 - Float16ConvertTest (ILLEGAL)
	  7 - GConvTest (Subprocess aborted)
	  9 - I8DepthwiseTest (ILLEGAL)
	 10 - I8SpmdmTest (ILLEGAL)
	 11 - Im2ColFusedRequantizeTest (ILLEGAL)
	 12 - PackedRequantizeAcc16Test (ILLEGAL)
	 13 - PackedRequantizeTest (ILLEGAL)
	 14 - QuantUtilsTest (ILLEGAL)
	 15 - RequantizeOnlyTest (ILLEGAL)
	 16 - RowWiseSparseAdagradFusedTest (Failed)
	 17 - SparseAdagradTest (Failed)
	 18 - SparseDenseMMFP32Test (ILLEGAL)
	 22 - TransposedRequantizeTest (ILLEGAL)
	 23 - UniConvTest (Failed)
```

**Comment by dskhudia** [comment]
These ILLEGAL failures seems to be related to you running on a cpu that doesn't support avx2 or above instruction set. FBGEMM needs at least avx2 instruction set support.

**Comment by adamjstewart** [comment]
Thanks, I added checks for this to our Spack package: https://github.com/spack/spack/pull/24356
