### ISSUE TITLE
Can fast BF16 <-> Float conversion be used at more places in PyTorch?

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/FBGEMM#632]
Currently, the vectorized BF16 <-> Float conversion in PyTorch is slower.

FBGEMM has faster conversion routines, and is being used in quantized kernels.
Can these routines for BF16 be used at more places in PyTorch?

Thank you!

**Comment by dskhudia** [comment]
Yes. Totally. PyTorch has conditional dependency on fbgemm, i.e., it can be built without fbgemm. As long as we keep the code inside #define USE_FBGEMM ... #endif (for example, https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cpu/qconv_prepack.cpp#L435-L441), we can use these functions. Feel free to create a PyTorch PR.

**Comment by imaginary-person** [comment]
@dskhudia, thanks for your advice!
BTW, I had tried doing so, but 4 `TestUnaryUfuncs` tests that compare output with `numpy` failed because the output was 0 instead of `nan`. I had modified `cvtfp32_bf16` like this -

```
inline __m256i QuantizeBF16Avx512(const __m512& x0) {
  // Add 2^15 and right shift 16 to do round-nearest
  __m512i y0 = _mm512_srli_epi32(
      _mm512_add_epi32(_mm512_castps_si512(x0), _mm512_set1_epi32(1 << 15)),
      16);
  return _mm512_cvtepi32_epi16(y0);
}

static inline __m512i cvtfp32_bf16(const __m512& a, const __m512& b) {
  // One float m512i -> One bfloat16 m256i
  __m512i retval;
  __m256i dst_reg0 = QuantizeBF16Avx512(a);
  __m256i dst_reg1 = QuantizeBF16Avx512(b);
  _mm256_storeu_si256(reinterpret_cast<__m256i*>(&retval), dst_reg0);
  _mm256_storeu_si256(reinterpret_cast<__m256i*>(&retval) + 1, dst_reg1);
  return retval;
}
```

**Comment by imaginary-person** [comment]
Reopening this issue to request further help with enabling faster `Float -> BFloat16` conversion routines. Thanks!

**Comment by dskhudia** [comment]
Will take a detailed look and respond soon.

**Comment by imaginary-person** [comment]
Sorry for the incomplete information, @dskhudia!
Over the weekend, I'll delve deeper into it & provide you clear information as to what's going on. Thank you!
