### ISSUE TITLE
Does cache size and instruction set the cpu support affect the performance of FBGEMM?

### ISSUE THREAD

**Issue by umiswing** [pytorch/FBGEMM#643]
I found my system get slower after switching to FBGEMM from OpenBLAS. I replaced the float matrix-matrix multiplication in OpenBLAS with Int8 matrix-matrix multiplication build with FBGEMM. But my system get slower after switching to the Int8 operation.
I set the thread number to 1 and test on the same machine.
I guess the cache size and the instruction set my cpu support affect the performance. My CPU is Intel Core i7-7500U, and it only supports avx2. The L1 cache size is 128 KB, L2 cache size is 512 KB and L3 cache size is 4.0MB.
I use the default Packing Parameters now.
I hope to speed up my system by using the Int8 matrix-matrix multiplication pipeline built with FBGEMM. But I am not sure what makes the Int8 version even slower. Should I switch to the CPU that support avx512 vnni? Or should I find the best params for my machine as #553 ?

**Comment by dskhudia** [comment]
Parameters can certainly help depending on the sizes of the matrices you are multiplying. Even with the defaults, you should have seen speedups. Could you build, run and post the results of https://github.com/pytorch/FBGEMM/blob/master/bench/GEMMsBenchmark.cc this benchmark and for fp32 GEMM use openBLAS in this benchmark?

**Comment by umiswing** [comment]
> 
> 
> Parameters can certainly help depending on the sizes of the matrices you are multiplying. Even with the defaults, you should have seen speedups. Could you build, run and post the results of https://github.com/pytorch/FBGEMM/blob/master/bench/GEMMsBenchmark.cc this benchmark and for fp32 GEMM use openBLAS in this benchmark?

OK. I read this benchmark and find it use MKL for fp32 GEMM. So I need to replace MKL with OpenBLAS, right? @dskhudia

**Comment by dskhudia** [comment]
> So I need to replace MKL with OpenBLAS, right?
Correct.

**Comment by umiswing** [comment]
I run the benchmark on my machine, using OpenBLAS for fp32 GEMM.
Following is the result:
|M| N|      K|             Type|  GOPS
|---|---|---|---|---|
|64|    800|    320|    OpenBLAS_fp32|  56.9
|64|    800|    320|  FBGEMM_i8_acc32| 119.4
|64|    800|    320|  FBGEMM_i8_acc16| 126.8
|64|    768|    512|    OpenBLAS_fp32|  41.6
|64|    768|    512|  FBGEMM_i8_acc32| 147.0
|64|    768|    512|  FBGEMM_i8_acc16| 158.7
|16|    256|    512|    OpenBLAS_fp32|  18.2
|16|    256|    512|  FBGEMM_i8_acc32|  67.7
|16|    256|    512|  FBGEMM_i8_acc16|  79.0
|128|    128|    128|    OpenBLAS_fp32|  46.3
|128|    128|    128|  FBGEMM_i8_acc32|  63.6
|128|    128|    128|  FBGEMM_i8_acc16|  82.1
|256|    512|    256|    OpenBLAS_fp32|  79.2
|256|    512|    256|  FBGEMM_i8_acc32| 152.7
|256|    512|    256|  FBGEMM_i8_acc16| 148.7
|1024|   1024|   1024|    OpenBLAS_fp32|  96.2
|1024|   1024|   1024|  FBGEMM_i8_acc32| 123.8
|1024|   1024|   1024|  FBGEMM_i8_acc16| 196.0

Speedups  can be seen in this benchmark. So I think it maybe the way I implement quantization lead to the slowdown in my system( I imitate Marian to do this ). I will check my code. Thanks very much for your help! @dskhudia
