### ISSUE TITLE
Do you have the plan of supporting Intel AMX instruction set on fbgemm backend?

### ISSUE THREAD

**Issue by xin3he** [pytorch/FBGEMM#649]
## 🚀 Feature

Support Intel AMX instruction set on fbgemm backend

## Motivation

AMX instruction is more efficient than before. we hope to use it in fbgemm backend when we are quantizing model to int8 with PyTorch.

## Pitch

We hope fbgemm support AMX instruction set so that we can use the same code without any change on a machine with AMX instruction set.

**Comment by dskhudia** [comment]
Hi @xin3he, 

We do but it's not high on the priority list. It will happen at sometime in future but probably in next few months.

**Comment by xin3he** [comment]
OK, thank you for your response.
