### ISSUE TITLE
embedding lookup jit in amd with avx2 is slower than non-jit kernel in handwritten

### ISSUE THREAD

**Issue by MichoChan** [pytorch/FBGEMM#669]
non-jit kernel in handwritten:
use avx2 and sse

AMD EPYC CPUs

**Comment by dskhudia** [comment]
I don't have access to AMD EPYC CPUs. Could you post the results and any analysis you did?

**Comment by MichoChan** [comment]
my test show that:
1) when normalize_by_lengths is true, the cvtsi2ss is too slow
2) when block_size(dim) is less 8, the jit kernel is slower than (sse + for loop)

**Comment by jspark1105** [comment]
@MichoChan thanks for reporting this issue. As Daya asked if you can share more info so we can reproduce it will be great. For example,
- can you share sse + for loop code you used?
- can you share what precision are you testing (fp32, fp16, int8, or int4)?

**Comment by MichoChan** [comment]
@jspark1105 

![image](https://user-images.githubusercontent.com/12822244/130346566-d9892722-68f3-4b03-bb39-c298b93f1863.png)

code just like above

I only test in fp16 and int8, the result:
![image](https://user-images.githubusercontent.com/12822244/130347081-8717d768-44f0-4aec-9724-89f9080c7641.png)

**Comment by jspark1105** [comment]
Thanks but can you please share in a form we can more easily reproduce like instead of screenshot we can't copy and paste, please share the code in text. Also, full code needed for reproduce. For example, do you mean bucket_size by number of embeddings in the table? What's the output_size/batch_size you used?

Anyway, one suspicion I have is code for remainder like https://github.com/pytorch/FBGEMM/blob/master/src/EmbeddingSpMDM.cc#L656-L676 is not optimized. We haven't paid much attention because block_size < 8 is not a common case. We'll try to look at this asap but unfortunately, ATM it may take sometime. So your contribution to optimize this meanwhile will be really appreciated.
Another option is at https://github.com/pytorch/FBGEMM/blob/master/src/EmbeddingSpMDM.cc#L874 we're calling a scalar code when block_size is 1, we can change this to block_size < 8 and use SSE code like yours.

**Comment by jspark1105** [comment]
I went ahead measure what I think what you implemented by changing EmbeddingSpMDMBenchmark on an Intel Skylake Xeon machine. I'm seeing JIT'ed code is faster for embedding_dim=5 (fp16). I think this perf issue is specific to AMD, but unfortunately we don't have much access to AMD. BTW, can you also share specific AMD EPYC CPU SKU you used?

```
fp16 inputs 32 bit indices with prefetching, lengths_sum 1046
            SLS    cache not flushed     prefetch on     b/w   8.85859 GB/s     effective b/w:          42.9344GB/s   time       1.6576e-06
            SLS        cache flushed     prefetch on     b/w   2.23906 GB/s     effective b/w:          10.8519GB/s   time       6.5581e-06
SIMD cache not flushed 11.2439GB/s
SIMD cache flushed 4.09954GB/s

Meanfp16 inputs 32 bit indices with prefetching, lengths_sum 1046
            SLS    cache not flushed     prefetch on     b/w   8.19694 GB/s     effective b/w:          39.7276GB/s   time       1.7914e-06
            SLS        cache flushed     prefetch on     b/w   2.07786 GB/s     effective b/w:          10.0706GB/s   time       7.0669e-06
SIMD cache not flushed 10.8456GB/s
SIMD cache flushed 4.27916GB/s
```

**Comment by MichoChan** [comment]
Thanks your analysis, the low perf is just in AMD. 
I'm trying to optimize this case, and I will share my work if it is optimized.

my tested AMD info:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    2
Core(s) per socket:    32
Socket(s):             2
NUMA node(s):          2
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 49
Model name:            AMD EPYC 7502 32-Core Processor
Stepping:              0
CPU MHz:               3344.035
CPU max MHz:           2500.0000
CPU min MHz:           1500.0000
BogoMIPS:              4990.56
Virtualization:        AMD-V
L1d cache:             32K
L1i cache:             32K
L2 cache:              512K
L3 cache:              16384K
NUMA node0 CPU(s):     0-31,64-95
NUMA node1 CPU(s):     32-63,96-127
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca
