### ISSUE TITLE
About fbgemm acceleration

### ISSUE THREAD

**Issue by nmanhong** [pytorch/FBGEMM#676]
Why do I test the faster-rcnn model in detectron2, there is almost no difference in the test time between opening fbgemm library and closing fbgemm, and closing mkldnn, I want to know where the fbgemm library accelerates

**Comment by nmanhong** [comment]
@dskhudia But I don’t use the api of fbgemm. There are cases provided by the government to test how much improvement it has compared to using and not using it.

**Comment by nmanhong** [comment]
@dskhudia But I do not use the api of fbgemm, where is there a case provided, let me test how much improvement is compared to use and not to use

**Comment by dskhudia** [comment]
How are you executing the model ?
