### ISSUE TITLE
PackBMatrix is too slow

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/FBGEMM#79]
I'm currently considering applying FBGEMM in a use case where the B matrix must be packed online (i.e. the weight matrix is dynamically computed). In my prototype, I've observed that I hit a bottleneck in PackBMatrix and when I investigate with perf, I see that most of the slowdown occurs because of multiple integer divisions in the inner loop.

I explored several optimization techniques and was able to get a 10x speedup on that routine. In summary I did:

- Loop invariant hoisting (move block offset calculation out of inner loop)
- Strength reduction (change modulus in inner loop to an increment + rollover)

This is the diff of PackBMatrix<>::pack()

```
     T* out = BaseType::getBuf() +
         g * this->packedBufferSize(block.row_size, block.col_size);
     for (int i = block.row_start; i < block.row_start + block.row_size; ++i) {
+      auto r = i;
+      int32_t block_row_id = r / BaseType::blockRowSize();
+      int32_t brow_offset = (block_row_id * BaseType::blockCols()) *
+          (BaseType::blockRowSize() * BaseType::blockColSize());
+
+      int32_t inblock_offset_row_cpt = (r % BaseType::blockRowSize() / row_interleave_) *
+              BaseType::blockColSize() * row_interleave_ + r % row_interleave_;
+
+      int32_t block_col_id = block.col_start / BaseType::blockColSize();
+      int32_t block_col_offs = block.col_start % BaseType::blockColSize();
       for (int j = block.col_start; j < block.col_start + block.col_size; ++j) {
         T val = tr ? smat_[i + (g * block.col_size + j) * ld_]
                    : smat_[(g * block.row_size + i) * ld_ + j];
-        out[addr(i, j)] = tconv(val, out[addr(i, j)]);
+        int32_t bcol_offset =
+            block_col_id * BaseType::blockRowSize() * BaseType::blockColSize();
+        int32_t block_offset = brow_offset + bcol_offset;
+        int32_t inblock_offset = inblock_offset_row_cpt + (block_col_offs) * row_interleave_;
+        int32_t index = block_offset + inblock_offset;
+        out[index] = tconv(val, out[index]);
+
+        block_col_offs++;
+        if (block_col_offs == BaseType::blockColSize()) {
+          block_col_offs = 0;
+          block_col_id++;
+        }
       }
     }
     // fill the remaining with zero.
```

This works for my purposes in an offline prototype, but I am not sure if the `addr()` API on `PackMatrix` is going to be used by others. This change moves the implementation of that API to be intertwined with the loop structure in `pack()`, so I'm not quite sure how to proceed here

**Comment by jianyuh** [comment]
Thanks @jamesr66a! We had a  Hackmonth task (T35337506) for this. The "addr" function is not efficient, because it makes compiler less likely to group several contiguous elements together to form vector loadu/storeu operations. The addr() API on PackBMatrix should only be used in printPackedMatrix, not be used by any other functions. We will incorporate your Diffs soon.

**Comment by jianyuh** [comment]
Fixed by https://github.com/pytorch/FBGEMM/commit/5720ee73bf2665a566e596eb8a0999629a91b213.
