### ISSUE TITLE
`make install` failing on V100 with Werror issue. 

### ISSUE THREAD

**Issue by amathews-amd** [pytorch/FBGEMM#896]
`make install` failing on V100 with Werror issue. 

```
/myworkspace/FAMBench/FBGEMM_local/bench/GEMMsBenchmark.cc: In function ‘void performance_test()’:
/myworkspace/FAMBench/FBGEMM_local/bench/GEMMsBenchmark.cc:136:24: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     for (auto i = 0; i < Cfp32_mkl.size(); ++i) {
                      ~~^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

**Comment by jianyuh** [comment]
Can you give more details on the repro? Is this for installing "fbgemm" (CPU) or "fbgemm_gpu" folder? I guess "V100" refers to V100 GPU so this is installing fbgemm_gpu folder?

**Comment by amathews-amd** [comment]
This is fbgemm (https://github.com/pytorch/FBGEMM/blob/main/bench/GEMMsBenchmark.cc). 
Apologies, the V100 does not make much sense here.

**Comment by jianyuh** [comment]
I see: this is FBGEMM CPU build. Which machine / OS / compiler did you use?

I checked the Circle CI tests for OSS builds and tests are running: 

https://app.circleci.com/pipelines/github/pytorch/FBGEMM/526/workflows/f7fb5160-3468-419b-a488-3e137b342c3e/jobs/907

The running commands are here:
https://github.com/pytorch/FBGEMM/blob/main/.circleci/config.yml#L24

**Comment by jianyuh** [comment]
Thanks for the fix!
