### ISSUE TITLE
[Bug] cpu_only fbgemm won't compile "permute_pooled_embs_auto_grad"

### ISSUE THREAD

**Issue by RabbitWhite1** [pytorch/FBGEMM#988]
As specified in [CMakeLists.txt](https://github.com/pytorch/FBGEMM/blob/c3a26e17e7c514041ae3d08f39d0e19063614869/fbgemm_gpu/CMakeLists.txt#L239), "src/permute_pooled_embedding_ops_gpu.cpp" will only compile when "NOT FBGEMM_CPU_ONLY", which means the method "permute_pooled_embs_auto_grad" won't be generated when `--cpu_only`. However, this method is used by torchrec's `column_wise` sharding.

The pr mentioned in #950 cannot work because of not using m.def to define `permute_pooled_embs_auto_grad`.

See the pull request #987 for details.

**Comment by jianyuh** [comment]
Thanks @RabbitWhite1 for reporting this issue! We are working on fixing this issue with https://github.com/pytorch/FBGEMM/pull/950 as you mentioned. Currently the major blocker on landing the PR is due to some internal backward compatibility issues. Will push on landing it soon. cc @geyyer

**Comment by jianyuh** [comment]
Sorry just saw your PR https://github.com/pytorch/FBGEMM/pull/987 . Thanks for your contributions!! Just a heads-up on the backward compatibility issue we are facing on delaying the PR landing process.

**Comment by geyyer** [comment]
@RabbitWhite1, thanks for contributing! The PR #987 landed, closing the issue.
